services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
  api:
    build: .
    command: npm run start:dev
    ports:
      - "3001:3001"
    volumes:
      - .:/usr/src/app
    depends_on:
      - db
    env_file:
      - .env